//Each new term in the Fibonacci sequence is generated by adding 
//the previous two terms. By starting with 1 and 2, the first 
// 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values 
// do not exceed four million, find the sum of the even-valued terms.


//Correct

public class problem02 {

	public int fibonacci(int n) {
		if(n == 0)
	        return 0;
	    else if(n == 1)
	      return 1;
	   else
	      return fibonacci(n - 1) + fibonacci(n - 2);
	}
	
	public static void main(String[] args) {
		problem02 fib = new problem02();
		
		int numberVal = 0;
		int count = 0;
		int answer = 0;
		while (numberVal < 4000000) {
			numberVal = fib.fibonacci(count);
			if (numberVal%2 == 0) {
				answer += numberVal;
			}
			count ++;
		}
		
		System.out.println(answer);
	}
}