import java.math.BigInteger;
import java.util.ArrayList;

//How many distinct terms are in the sequence
//generated by a^b for 2 ² a ² 100 and 2 ² b ² 100?

public class problem29 {

	public static void main(String[] args) {
		
		long startTime = System.currentTimeMillis();
		
		ArrayList<BigInteger> termSequence = new ArrayList<BigInteger>();
		
		for (int a = 2; a <= 100; a ++) {
			
			for (int b = 2; b <= 100; b ++ ){
				
				BigInteger term = BigInteger.valueOf(a).pow(b);
				
				if (!termSequence.contains(term)) {
					termSequence.add(term);
				}		
			}		
		}
		
		System.out.println(termSequence.size());
		
		System.out.println("Total elapsed time: " + (System.currentTimeMillis() - startTime) +"ms");
	}
}
